// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whvtzxhodwherpsjvbyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodnR6eGhvZHdoZXJwc2p2YnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDEyNzUsImV4cCI6MjA2OTAxNzI3NX0.1YRXKfHgwpsN8eYnmMdBC-OG6xKeROfiD17NRKW4168";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});